CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE organizations
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_key    UUID         NOT NULL DEFAULT gen_random_uuid(),
    code            VARCHAR(100) NOT NULL,
    name            VARCHAR(255) NOT NULL,
    parent_id       BIGINT,
    status          VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    version         BIGINT       NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),

    CONSTRAINT uk_organizations_business_key UNIQUE (business_key),
    CONSTRAINT uk_organizations_code UNIQUE (code),

    CONSTRAINT fk_organizations_parent
        FOREIGN KEY (parent_id)
            REFERENCES organizations (id),

    CONSTRAINT chk_organizations_status
        CHECK (status IN ('ACTIVE', 'ARCHIVED'))
);

CREATE INDEX idx_organizations_parent_id
    ON organizations (parent_id);

CREATE INDEX idx_organizations_status
    ON organizations (status);


CREATE TABLE user_accounts
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_key    UUID         NOT NULL DEFAULT gen_random_uuid(),
    external_id     VARCHAR(100),
    username        VARCHAR(100) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    first_name      VARCHAR(100),
    last_name       VARCHAR(100),
    organization_id BIGINT,
    status          VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    version         BIGINT       NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),

    CONSTRAINT uk_user_accounts_business_key UNIQUE (business_key),
    CONSTRAINT uk_user_accounts_external_id UNIQUE (external_id),
    CONSTRAINT uk_user_accounts_username UNIQUE (username),
    CONSTRAINT uk_user_accounts_email UNIQUE (email),

    CONSTRAINT fk_user_accounts_organization
        FOREIGN KEY (organization_id)
            REFERENCES organizations (id),

    CONSTRAINT chk_user_accounts_status
        CHECK (status IN ('ACTIVE', 'BLOCKED', 'ARCHIVED'))
);

CREATE INDEX idx_user_accounts_organization_id
    ON user_accounts (organization_id);

CREATE INDEX idx_user_accounts_status
    ON user_accounts (status);


CREATE TABLE roles
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_key    UUID         NOT NULL DEFAULT gen_random_uuid(),
    code            VARCHAR(100) NOT NULL,
    name            VARCHAR(255) NOT NULL,
    description     TEXT,
    system_role     BOOLEAN      NOT NULL DEFAULT FALSE,
    status          VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    version         BIGINT       NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),

    CONSTRAINT uk_roles_business_key UNIQUE (business_key),
    CONSTRAINT uk_roles_code UNIQUE (code),

    CONSTRAINT chk_roles_status
        CHECK (status IN ('ACTIVE', 'ARCHIVED'))
);


CREATE TABLE permissions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_key    UUID         NOT NULL DEFAULT gen_random_uuid(),
    code            VARCHAR(150) NOT NULL,
    name            VARCHAR(255) NOT NULL,
    description     TEXT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_permissions_business_key UNIQUE (business_key),
    CONSTRAINT uk_permissions_code UNIQUE (code)
);


CREATE TABLE user_roles
(
    user_id         BIGINT      NOT NULL,
    role_id         BIGINT      NOT NULL,
    valid_from      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valid_to        TIMESTAMPTZ,
    assigned_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_by     VARCHAR(255),

    PRIMARY KEY (user_id, role_id),

    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id)
            REFERENCES user_accounts (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id)
            REFERENCES roles (id)
            ON DELETE CASCADE,

    CONSTRAINT chk_user_roles_valid_period
        CHECK (valid_to IS NULL OR valid_to > valid_from)
);

CREATE INDEX idx_user_roles_role_id
    ON user_roles (role_id);


CREATE TABLE role_permissions
(
    role_id         BIGINT      NOT NULL,
    permission_id   BIGINT      NOT NULL,
    granted_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    granted_by      VARCHAR(255),

    PRIMARY KEY (role_id, permission_id),

    CONSTRAINT fk_role_permissions_role
        FOREIGN KEY (role_id)
            REFERENCES roles (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_role_permissions_permission
        FOREIGN KEY (permission_id)
            REFERENCES permissions (id)
            ON DELETE CASCADE
);

CREATE INDEX idx_role_permissions_permission_id
    ON role_permissions (permission_id);
